-- ============================================================
-- Importar inventario real desde Inventario_Distribuidora_LimpiezaPro.xlsx
-- Generado automáticamente. 142 productos, un solo bloque (sin zonas).
-- Ejecutar en: Supabase → SQL Editor → New query
-- ============================================================

-- 1) Unidades de medida nuevas que aparecen en el Excel
insert into unidades_medida (nombre) values
  ('cajas (12 und)'),
  ('cajas (1 und)'),
  ('planchas'),
  ('cajas'),
  ('cajas (24 und c/u)'),
  ('rollos'),
  ('rollos (12x1)'),
  ('bolsas'),
  ('kit'),
  ('kit (mopa+palo)'),
  ('paq (7 und c/u)'),
  ('bolsas (1 kg c/u)')
on conflict (nombre) do nothing;

-- 2) Datos crudos del Excel (nombre, código, unidad, cantidad real, observación)
with datos (nombre, codigo, unidad_nombre, cantidad_inicial, observacion) as (
  values
    ('Papel Higiénico Súper 500ml x4', '004/023323', 'und', 152, null),
    ('Papel Higiénico Clásico x2', '22134', 'und', 100, 'Verificar cantidad (letra poco clara)'),
    ('PH Súper x4x4x250ml', '013554', 'und', 40, 'Verificar código/cantidad'),
    ('Papel Toalla interfoliado x4x8 hojas', '361660', 'cajas (12 und)', 12, null),
    ('Servilleta Cortada x1000 und', '361614', 'cajas (1 und)', 27, null),
    ('Servilleta Élite Doblada en 4 Plus', '360936', 'paq', 28, null),
    ('Papel Higiénico Élite 500ml x4 Excellence', '361377', 'paq', 2, null),
    ('Servilletero Súper 100ml x2', '23619', 'und', 39, 'Verificar cantidad'),
    ('Papel Higiénico Élite 500ml x2', '36707', 'paq', 227, null),
    ('Papel Toalla Clásico 200ml x2', '36791', 'und', 265, null),
    ('Papel Toalla Súper Ecológico 200ml x2', '215583', 'paq', 190, null),
    ('Papel Toalla Élite Plus x2', '361043', 'paq', 95, 'Nota original: ''95 pag - 4pts+4'''),
    ('Servilleta Clásico Élite 18x300', '360425', 'planchas', 129, null),
    ('Papel Higiénico Súper 550ml x2', '23592', 'paq', 98, null),
    ('Papel Higiénico Élite 300ml x2', '361683', 'paq', 10, null),
    ('Centímetro (rollo) 20 rollos', null, 'cajas', 65, 'Verificar nombre de producto'),
    ('Papel Toalla Súper 300ml x4 rollos', '22001', 'paq', 15, null),
    ('Servilleta Élite Doblada en 4 - 33x33 (24 und)', '36005', 'cajas (24 und c/u)', 11, null),
    ('Papel Toalla Torx x2 rollos/120ml', '23748', 'paq', 27, null),
    ('Papel Higiénico Torx 200ml x2', '9161', 'paq', 25, null),
    ('Jabón Torx Espuma Antibacterial x1000ml', '30341', 'und', 30, null),
    ('Jabón Torx Espuma x1000 und', '30330', 'und', 30, null),
    ('Servilleta Gourmet x12 und', '36133', 'paq', 10, 'Verificar cantidad'),
    ('Servilletero Élite 200ml', '36761', 'paq', 18, null),
    ('Bolsa Rollo 5x10', null, 'rollos', 60, null),
    ('Bolsa Rollo 7x10', null, 'rollos', 60, null),
    ('Bolsa Rollo 8x12', null, 'rollos', 59, null),
    ('Bolsa Rollo 10x15', null, 'rollos', 59, null),
    ('Bolsa Rollo 12x17', null, 'rollos (12x1)', 60, null),
    ('Desengrasante Dabiza 3.8 (galón)', null, 'und', 34, null),
    ('Jabón Súper 5LT', null, 'und', 23, null),
    ('Panosina 24LT y 6 rollo', null, 'paq', 5, 'Verificar descripción'),
    ('Detergente CPA 4LT', null, 'bolsas', 10, null),
    ('Alcohol 70°', null, 'und', 4, null),
    ('Limpiavidrios Maya 3.8', null, 'und', 16, null),
    ('Jabón Fasca Maya 3.8', null, 'und', 12, null),
    ('Servilleta Plus 33x33', '361699', 'und', 10, null),
    ('Balde + Mopa + Palo (kit)', null, 'kit', 72, 'Verificar cantidad'),
    ('Bolsas 240L 4pza x100 Unitex', null, 'planchas', 30, null),
    ('Lavavajilla 3.8LT Unitex', null, 'und', 61, 'Código anotado como ''GN.56'', verificar'),
    ('Sacagrasa 3.8LT Unitex', null, 'und', 61, 'Código anotado ''61N.39'', verificar'),
    ('Limpiador Bambú 3.8LT Unitex', null, 'und', 61, 'Código anotado ''61N.25'', verificar'),
    ('Limpiador BaBa 3.8LT Unitex', null, 'und', 61, 'Código anotado ''61N.37'', verificar'),
    ('Limpiador Lavanda 3.8LT Unitex', null, 'und', 22, 'Código anotado ''GN'', verificar'),
    ('Pastillas Baño Lavanda x2 Unitex', null, 'und', 72, null),
    ('Limpiador Pinesol 1.8LT Unitex', null, 'und', 24, null),
    ('Limpiador Lavanda 1.8LT Unitex', null, 'und', 13, null),
    ('Paño Absorbente x20 Unitex', null, 'und', 4, 'Verificar cantidad'),
    ('Mopa #16 y Palo Unitex', null, 'kit (mopa+palo)', 70, null),
    ('Guante Baño Lavandería ''L''', null, 'und', 24, null),
    ('Guante Baño Lavandería ''M''', null, 'und', 24, null),
    ('Recogedor Metal-Plástico Unitex', null, 'und', 21, null),
    ('Recogedor Económico Unitex', null, 'und', 20, null),
    ('Recogedor Palo Reforzado Unitex', null, 'und', 48, null),
    ('Recogedor Desyerba', null, 'und', 24, 'Verificar nombre'),
    ('Popsi Mixta Élite 1kg x30', '361661', 'paq', 14, null),
    ('Maxigasa x50 Unitex', '30732', 'rollos', 8, null),
    ('Cloro 400ml Lavaflex', null, 'und', 180, null),
    ('Rad Cocktail Nuevo', null, 'und', 6, 'Verificar nombre/cantidad, aparece ''6 UND 36'''),
    ('Rayo Ron Vinilo 480ml', null, 'und', 60, null),
    ('Raid Doblación 400ml', null, 'und', 36, null),
    ('Guante Profesional M 0.35 Unitex', null, 'und', 24, null),
    ('Guante Largo ''L'' 0.35 Unitex', null, 'und', 36, null),
    ('Guante Largo ''M'' 0.35 Unitex', null, 'und', 36, null),
    ('Guante Cargador ''L'' Unitex', null, 'und', 24, null),
    ('Guante Cargador ''M'' Unitex', null, 'und', 48, null),
    ('Cepillo Pequeño Unitex', null, 'und', 24, null),
    ('Fibra Verde y Limpieza Unitex', null, 'und', 178, null),
    ('Fibra Esponja x7 Unitex', null, 'und', 6, 'Verificar cantidad (ilegible)'),
    ('Mopa #16 Repuesto', null, 'und', 121, null),
    ('Lavavajilla Limón Mg 900ml', null, 'und', 30, null),
    ('Limpiador Crema 750ml Unitex', null, 'und', 12, null),
    ('Esponja Fibra Delicada x100 Unitex', null, 'und', 27, null),
    ('Esponja Extra Fuerte x18 Unitex', null, 'und', 36, null),
    ('Escoba Podona Unitex', null, 'und', 67, null),
    ('Guante Multiuso Impermeable', null, 'und', 97, null),
    ('Limpia Sanitario Unitex x12', null, 'und', 36, null),
    ('Lejía Bidón Hoja', null, 'und', 4, null),
    ('Removedor daryza 3.8lt', null, 'und', 5, null),
    ('Lejía gln maja', null, 'und', 13, null),
    ('Limpia inodoro daryza  3.8LT', null, 'und', 8, null),
    ('Paño Esponja x12', null, 'und', 28, null),
    ('Jabón Élite Fantomático', '367173/367165', 'und', 270, 'Verificar código exacto'),
    ('Jabón Espuma Excellence', '371173', 'und', 132, null),
    ('Jaca Blanca Malatto x100', null, 'und', 218, null),
    ('Film Cocina 30.5x305', null, 'und', 1, null),
    ('Film Cocina 30.5x609', null, 'und', 1, null),
    ('Film Cocina 96x600', null, 'und', 1, null),
    ('Film Cocina 35x300x1400', null, 'und', 1, null),
    ('Film Cocina 35x380x1400', null, 'und', 1, null),
    ('Film Cocina 35x450x1400', null, 'und', 1, null),
    ('Bolsa 24LT Pollo virutex', null, 'und', 60, null),
    ('Bolsa 20LT Pollo virutex', null, 'und', 24, 'Aparece nota adicional ''139'', verificar'),
    ('Bolsa 40LT Rollo virutex', null, 'und', 55, null),
    ('Bolsa 75LT Pollo virutex', null, 'und', 60, null),
    ('Bolsa 50LT Pollo virutex', null, 'und', 200, null),
    ('Bolsa 35LT Pollo virutex', null, 'und', 92, null),
    ('Paño Higiénico x4 virutex', null, 'und', 144, null),
    ('Limpiador Floral 3.8L virutex', null, 'und', 4, 'Verificar cantidad'),
    ('Bouquet Verde 300ml', null, 'und', 56, null),
    ('Limpiador Panorama 3.3L Unitex', null, 'und', 44, null),
    ('Papel Absorbente x20 (5 hojas/muda)', null, 'und', 96, null),
    ('Papel Absorbente x20', null, 'und', 360, null),
    ('Súper Dalia Verde Unitex', null, 'und', 720, null),
    ('Súper Dalia Roja Unitex', null, 'und', 100, 'Verificar cantidad'),
    ('Bolsa Polietileno 26x40 x100', null, 'und', 100, null),
    ('Bolsa Polietileno 20x30 x100', null, 'und', 100, null),
    ('Bolsa 140LT x100 Unitex', null, 'und', 28, null),
    ('Jabón Glicerina Élite', '371628', 'und', 72, null),
    ('Alcohol Gel Élite', '371626', 'und', 84, null),
    ('Jabón Antibacterial Élite', '371625', 'und', 580, null),
    ('Servilleta Doblada en 4 30x40', '360442', 'und', 100, null),
    ('Servilleta 33x33', '361699', 'und', 100, null),
    ('Servilleta Ecológica 33x22.5', '361704', 'und', 360, null),
    ('Servilleta Interfoliada Élite', '36160', 'paq (7 und c/u)', 56, null),
    ('Canastillo Urinario', null, 'und', 100, null),
    ('Papel Toalla Interfoliado Súper', '25933', 'und', 373, null),
    ('Desatorador de Baño Unitex', null, 'und', 24, null),
    ('Trapeador Microfibra Ojal 40x40', null, 'und', 960, null),
    ('Paño Microfibra 30x30 Azul', null, 'und', 230, null),
    ('Paño Microfibra 30x30 Gris', null, 'und', 22, null),
    ('Paño Microfibra 30x30 Verde', null, 'und', 24, null),
    ('Paño Microfibra 30x30 Rojo', null, 'und', 24, null),
    ('Paño Microfibra 30x30 Naranja', null, 'und', 3, null),
    ('Paño Microfibra 30x30 Amarillo', null, 'und', 21, null),
    ('Paño Microfibra 40x40 Amarillo', null, 'und', 24, null),
    ('Paño Microfibra 40x40 Naranja', null, 'und', 24, null),
    ('Paño Microfibra 40x40 Gris', null, 'und', 24, null),
    ('Paño Microfibra 40x40 Verde', null, 'und', 12, null),
    ('Trapo Industrial', null, 'bolsas (1 kg c/u)', 10, null),
    ('Papel Higiénico Élite Perfumado x24', '367166', 'paq', 26, null),
    ('Papel Toalla Multipoder Clásico x8', '361536', 'paq', 40, null),
    ('Guante Nitrilo ''H'' Anjion', null, 'und', 500, 'Verificar nombre de marca'),
    ('Guante Nitrilo ''J''', null, 'und', 930, null),
    ('Esponja Scotch Brite 3M', '367199', 'und', 120, null),
    ('Guante Nitrilo ''L'' Metallix', null, 'und', 30, 'Verificar nombre'),
    ('Guante Látex ''H'' Multitallo', null, 'und', 14, null),
    ('Guante Talla ''L'' Multitallo', null, 'und', 5, null),
    ('Guante Látex ''L'' Alfajor', null, 'und', 5, 'Verificar nombre/marca'),
    ('Lavavajilla Pasta Sapolio Jabón', null, 'und', 9, null),
    ('Guante Látex ''L''', null, 'und', 20, null),
    ('Guante Nitrilo ''M''', null, 'und', 200, null)
),
-- 3) Crear los productos (cantidad y costo arrancan en 0, se llenan por el movimiento de abajo)
nuevos_productos as (
  insert into productos (nombre, codigo, unidad_id, categoria_id, zona_id, cantidad, costo, observacion)
  select d.nombre, d.codigo, u.id, null, null, 0, 0, d.observacion
  from datos d
  join unidades_medida u on u.nombre = d.unidad_nombre
  returning id, nombre, codigo
)
-- 4) Registrar la carga inicial como movimiento de "entrada" (costo desconocido, se corrige después con compras reales)
insert into movimientos (producto_id, tipo, cantidad, costo_unitario, motivo)
select np.id, 'entrada', d.cantidad_inicial, 0, 'Carga inicial de inventario (Excel)'
from nuevos_productos np
join datos d on d.nombre = np.nombre and coalesce(d.codigo, '') = coalesce(np.codigo, '');
